### PR TITLE
update w/latest changes to 1.10 branch

### PR DESCRIPTION
**Pull request by wkeese**
generated data against latest 1.10.  hmm, not sure why there are so many changes though.

### CODE REVIEW

**Comment by lbod** [comment]
Your doc changes to dijit/form look fine, not sure what's going on with dojox/Calendar changes..

And it looks like the docparser couldn't handle the changes to dojox/encoding/digests in https://github.com/dojo/dojox/commit/f8273c955e892ec21fbe10322508ddb362051a60 @jason0x43

**Comment by wkeese** [comment]
Thanks for tracking down dojo/dojox@f8273c9 @jason0x43.  So we lost the API doc for SHA224, SHA256, SHA384, and SHA512.  For example, the old doc for SHA224 is https://dojotoolkit.org/api/1.10/dojox/encoding/digests/SHA224.html.   I guess there wasn't that much there before anyway.

**Comment by jason0x43** [comment]
There wasn't any explicit documentation before, just the module objects (`SHA256`, etc.) themselves. The updated digest code doesn't create objects for individual SHA2 algorithms anymore, it generates implementations on demand when one of the `SHAXXX` modules is loaded, so there's nothing there for the docparser to inspect.

**Comment by wkeese** [comment]
jason0x43 - Yes, I understand, but at least it showed up in the API doc as:

```
Usage:
SHA224(data,outputType);
Parameter   Type    Description
data    String  
outputType  sha32.outputTypes   Optional
```

And now it doesn't.

**Comment by wkeese** [comment]
@lbod wrote:

> not sure what's going on with dojox/Calendar changes..

Ah OK, I screwed up here.  the problem is that even when I do `git checkout 1.10`, calendar is still on master because it's a git external, pointing to https://github.com/damiengarbarino/dojo-calendar.  Looks like I also needed to do a `git submodule update`.  Submodules are really annoying.

I pushed a newer version to https://github.com/wkeese/dojo-site-api/commit/0e1030067ae2288609ba42538c576a783bd56c49.

**Pull request merged**
